### ISSUE TITLE
Missing image in Mentor Section

### ISSUE THREAD

**Issue by vashukashyap** [ElixirTechCommunity/ElixirV3#1]
# issue
Image of Abhinav Yadav is missing in mentor section.
![Screenshot Capture - 2024-09-10 - 00-41-43](https://github.com/user-attachments/assets/58a3049b-1084-4287-a9a5-19184d4f4acc)

## Step to reproduce
* visit the  https://www.elixircommunity.in/mentors
* Scroll down to Abhinav Yadav.

### Image Source
https://media.licdn.com/dms/image/v2/C4D03AQFEg6wfK03Q3w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1641145585177?e=1731542400&v=beta&t=drGlSr34S9TskCUz3QZoaiiyoKpTGP4_neB2ZmtgRyw

**Comment by Vikram-Singh0** [comment]
Assign this issue
